name: assignment_flutter
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.1
  connectivity_plus: ^2.3.0
  provider: ^6.0.3

  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  shared_preferences: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_datetime_picker: ^1.5.1
  flutter_swipe_action_cell: ^3.0.4
  encrypt: ^5.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.2
  build_runner:
  flutter_gen_runner:

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/png/


